produccion/urls.py
from django.urls import path, register_converter

from . import converts, views

register_converter(converts.FloatUrlParameterConverter, 'float')


urlpatterns = [
     path('', views.ProduccionIndexView.as_view(), name='produccion-index'),
     path('nuevo/', views.ProduccionNuevoView.as_view(), name='produccion-nuevo'),
     path('produccion-cargas/<float:min>/<float:max>/<int:pagado>/',
          views.ProduccionCargasView.as_view(), name="produccion-cargas"),
     path('ver/<pk>/', views.ProduccionView.as_view(),
          name="produccion-cargas-view"),
     path('carga/entregar/<pk>/', views.ProduccionEntregaView.as_view(),
          name="produccion-entrega-view"),
     path('carga/eliminar/<pk>/', views.ProduccionCargaRemoveView.as_view(),
          name="produccion-carga-remove"),
     path('reporte/<pk>/', views.ReporteProduccion.as_view(),
          name="produccion-reporte"),
     path('produccion/sin-procesar/', views.ReporteProduccionCancha.as_view(),
         name="produccion-reporte-cancha")
]

user/urls.py
from django.urls import path
from django.conf.urls import url

from django.contrib.auth import views as auth_views

from .views import CotizacionDeleteView, CotizacionListJson, CotizacionUpdateView, CreateUserView, DestinoProduccionCreateView, DestinoProduccionListView, DestinoProduccionUpdateView, GeneradorPrintExcel, ParametroView, ProfileUpdateView, ConfiguracionView, UserEditView, UserListView, CotizacionCreateView, \
    DestinoCreateView, DestinoListView, DestinoUpdateView, LaboratorioListView, LaboratorioCreateView, LaboratorioUpdateView, GeneradorListJson, GeneradorCreateView, GeneradorPrintView, \
    UbicacionView, LaboratorioView, OrigenListView, OrigenCreateView, OrigenUpdateView, CodigoAutoComplete, FactorCreateView, FactorListView, FactorUpdateView

urlpatterns = [
    path('configuracion/', ConfiguracionView.as_view(), name='user-configuracion'),
    path('create/', CreateUserView.as_view(), name='user-create'),
    path('list/', UserListView.as_view(), name='user-list'),
    path('profile/<pk>/', ProfileUpdateView.as_view(), name='user-profile'),
    path('edit/<pk>/', UserEditView.as_view(), name='user-edit'),
    path('parametro/', ParametroView.as_view(), name='parametro-index'),
    path('parametro/ubicacion/', UbicacionView.as_view(),
         name='parametro-ubicacion-index'),
    path('parametro/laboratorio/', LaboratorioView.as_view(),
         name='parametro-laboratorio-index'),
    path('parametro/cotizacion/create/',
         CotizacionCreateView.as_view(), name='cotizacion-create'),
    path('parametro/cotizacion/edit/<pk>/',
         CotizacionUpdateView.as_view(), name='cotizacion-edit'),
    path('parametro/cotizacion/delete/<pk>/',
         CotizacionDeleteView.as_view(), name='cotizacion-delete'),
    url(r'^parametro/cotizacion/json/$',
        CotizacionListJson.as_view(), name='cotizacion-json'),
    path('parametro/origen/list/',
         OrigenListView.as_view(), name='origen-list'),
    path('parametro/origen/create/',
         OrigenCreateView.as_view(), name='origen-create'),
    path('parametro/origen/edit/<pk>/',
         OrigenUpdateView.as_view(), name='origen-edit'),
    path('parametro/destino/list/',
         DestinoListView.as_view(), name='destino-list'),
    path('parametro/destino/create/',
         DestinoCreateView.as_view(), name='destino-create'),
    path('parametro/destino/edit/<pk>/',
         DestinoUpdateView.as_view(), name='destino-edit'),
    path('parametro/destinoproduccion/list/',
         DestinoProduccionListView .as_view(), name='destinoproduccion-list'),
    path('parametro/destinoproduccion/create/',
         DestinoProduccionCreateView.as_view(), name='destinoproduccion-create'),
    path('parametro/destinoproduccion/edit/<pk>/',
         DestinoProduccionUpdateView.as_view(), name='destinoproduccion-edit'),
    path('parametro/laboratorio/list/',
         LaboratorioListView.as_view(), name='laboratorio-list'),
    path('parametro/laboratorio/create/',
         LaboratorioCreateView.as_view(), name='laboratorio-create'),
    path('parametro/laboratorio/edit/<pk>/',
         LaboratorioUpdateView.as_view(), name='laboratorio-edit'),
    url(r'^parametro/generador/json/$',
        GeneradorListJson.as_view(), name='generador-json'),
    path('parametro/generador/create/',
         GeneradorCreateView.as_view(), name='generador-create'),
    path('parametro/generador/reporte/<pk>/',
         GeneradorPrintView.as_view(), name='generador-reporte'),
    path('parametro/generador/reporte-excel/<pk>/',
         GeneradorPrintExcel.as_view(), name='generador-reporte-excel'),
    url(r'^codigo-autocomplete/$', CodigoAutoComplete.as_view(),
        name='codigo-autocomplete'),
    path('parametro/factor/create/',
         FactorCreateView.as_view(), name='factor-create'),
    path('parametro/factor/edit/<pk>/',
         FactorUpdateView.as_view(), name='factor-edit'),
    path('parametro/factor/list/',
         FactorListView.as_view(), name='factor-list'),
    path(
        'change-password/',
        auth_views.PasswordChangeView.as_view(
            template_name='user/change-password.html',
            success_url='/user/logout/'
        ),
        name='change_password_personal'
    ),
]

pesaje/models.py
import uuid
from django.db import models
from django.db.models import Q
from django.db.models.query import QuerySet
import datetime
# Create your models here.
from proveedor.models import Proveedor
from conductor.models import Vehiculo, Conductor
from user.models import CustomUser, Destino, Factor, Laboratorio, Origen
from produccion.models import Produccion

TIPO_CARGA = (
    ('NORMAL', 'NORMAL'),
    ('LAMA', 'LAMA')
)


class MyModelMixin(object):

    def q_for_search_word(self, word):
        return Q(numero__contains=word)

    def q_for_search(self, search):
        q = Q()
        if search:
            searches = search.split()
            for word in searches:
                q = q & self.q_for_search_word(word)
        return q

    def filter_on_search(self, search):
        return self.filter(self.q_for_search(search))


class MyModelQuerySet(QuerySet, MyModelMixin):
    pass


class MyModelManager(models.Manager, MyModelMixin):

    def get_queryset(self):
        return MyModelQuerySet(self.model, using=self._db)


class Carga(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    usuario = models.ForeignKey(CustomUser, on_delete=models.CASCADE)
    vehiculo = models.ForeignKey(
        Vehiculo, related_name='vehiculo', on_delete=models.CASCADE)
    conductor_vehiculo = models.ForeignKey(
        Conductor, related_name='conductor_vehiculo', on_delete=models.CASCADE)
    proveedor = models.ForeignKey(Proveedor, on_delete=models.CASCADE)
    origen = models.ForeignKey(Origen, on_delete=models.CASCADE)
    equipo_carguio = models.ForeignKey(
        Vehiculo, related_name='carguio', on_delete=models.CASCADE, null=True)
    destino = models.ForeignKey(Destino, on_delete=models.CASCADE)
    peso_bruto = models.FloatField(default=0)
    peso_tara = models.FloatField(default=0)
    peso_neto = models.FloatField(default=0)
    peso_neto_tn = models.FloatField(default=0)
    numero = models.CharField(max_length=20, unique=True)
    pesaje = models.BooleanField(default=False)
    pesaje_bruto = models.BooleanField(default=True)
    pesaje_tara = models.BooleanField(default=False)
    numero_paleta = models.CharField(max_length=10, default='')
    color = models.CharField(max_length=50, default='')
    fecha_paleta = models.DateField(null=True, blank=True)
    paleta = models.BooleanField(default=False)
    laboratorio = models.BooleanField(default=False)
    au = models.FloatField(default=0)
    h2o = models.FloatField(default=0)
    porcentaje_tamanos = models.FloatField(default=0)
    cobre_soluble = models.FloatField(default=0)
    tipo_carga = models.CharField(
        max_length=10, choices=TIPO_CARGA, default='NORMAL')
    tms = models.FloatField(default=0)
    tms_neta = models.FloatField(default=0)
    tms_penalizar = models.FloatField(default=0)
    tms_pagar = models.FloatField(default=0)
    finos_gr = models.FloatField(default=0)
    finos_gr_recup = models.FloatField(default=0)
    finos_oz = models.FloatField(default=0)
    cotizacion = models.FloatField(default=0)
    calculo_regalia = models.FloatField(default=0)
    recu_planta = models.FloatField(default=0)
    valor_venta = models.FloatField(default=0)
    costo_tratamiento = models.FloatField(default=0)
    total_liquidacion_prov = models.FloatField(default=0)
    regalia = models.FloatField(default=0)
    penalizacion_cu_soluble = models.FloatField(default=0)
    #cambios laboratorio para su control
    fecha_laboratorio = models.DateTimeField(blank=True, null=True)
    fecha_laboratorio_modificaciones = models.TextField(blank=True, null=True)
    oro_soluble = models.FloatField(default=0)
    ratio = models.FloatField(default=0)
    fecha_muestreo = models.DateField(null=True, blank=True)
    # desde este punto pago de contador
    anticipo = models.FloatField(default=0)
    equipo_pesado = models.FloatField(default=0)
    balanza = models.FloatField(default=0)
    volqueta = models.FloatField(default=0)
    analisis_laboratorio = models.FloatField(default=0)
    otros_descuentos = models.FloatField(default=0)
    retencion_acuerdo = models.FloatField(default=0)
    retencion_acuerdo_vol = models.BooleanField(default=False)
    valor_reposicion = models.FloatField(default=0)
    total_descuento = models.FloatField(default=0)
    liquido_pagable = models.FloatField(default=0)
    observaciones = models.TextField(blank=True)
    pagado = models.BooleanField(default=False)
    fecha_pago = models.DateTimeField(blank=True, null=True)
    produccion = models.ForeignKey(
        Produccion, on_delete=models.SET_NULL, blank=True, null=True)
    estado_produccion = models.BooleanField(default=False)
    deleted = models.BooleanField(default=False)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    objects = MyModelManager()

    def clean(self):
        self.color = self.color.upper()

    def calcular_total(self):
        self.tms = self.peso_neto_tn*(100 - self.h2o)/100
        if self.porcentaje_tamanos > 4:
            self.tms_neta = self.tms - \
                (self.tms * self.porcentaje_tamanos)/100
        else:
            self.tms_neta = self.tms
        if self.cobre_soluble > 800:
            self.tms_penalizar = self.tms_neta
        else:
            self.tms_penalizar = 0
        self.tms_pagar = round(
            self.tms_neta - self.tms_penalizar, 2)
        self.finos_gr = self.tms_pagar * self.au
        self.finos_oz = self.finos_gr / 31.1035
        if self.tipo_carga == 'LAMA' and self.au < 3:
            self.finos_gr_recup = 0
        else:
            factor = Factor.objects.filter(
                rango_inferior__lte=self.au, rango_superior__gte=self.au)
            if factor:
                self.finos_gr_recup = round(factor[0].factor_recuperacion *
                                            self.finos_gr, 2)
        self.calculo_regalia = self.finos_oz * self.cotizacion * 6.96
        if self.tipo_carga == 'LAMA' and self.au < 3:
            self.recu_planta = 0
        else:
            if self.tipo_carga == 'NORMAL' and self.au < 1:
                self.recu_planta = 0
            else:
                factor = Factor.objects.filter(
                    rango_inferior__lte=self.au, rango_superior__gte=self.au)
                if factor:
                    self.recu_planta = factor[0].factor_recuperacion * \
                        self.finos_oz

        self.valor_venta = round(
            self.cotizacion * self.recu_planta * 6.96 * 0.94, 0)

        if self.au >= 10:
            self.costo_tratamiento = round(
                self.valor_venta * 0.52, 0)
        else:
            self.costo_tratamiento = round(
                self.valor_venta * 0.50, 0)
        self.total_liquidacion_prov = self.valor_venta - self.costo_tratamiento

        if self.recu_planta <= 0:
            self.regalia = 0
        else:
            if self.au >= 1 and self.au <= 2:
                self.regalia = round(
                    self.calculo_regalia * 0.042 * 0.9, 0)
            else:
                self.regalia = round(
                    self.calculo_regalia * 0.042 * 1, 0)

        if self.cobre_soluble >= 150 and self.cobre_soluble <= 800:
            self.penalizacion_cu_soluble = round(
                (0.0089 * self.cobre_soluble - 1.325) * 30 * self.tms_pagar, 0)
        else:
            self.penalizacion_cu_soluble = 0

        if self.retencion_acuerdo_vol:
            self.retencion_acuerdo = round(self.costo_tratamiento * 0.05, 0)
        else:
            self.retencion_acuerdo = 0
        self.total_descuento = self.regalia + self.penalizacion_cu_soluble + self.anticipo + self.equipo_pesado + self.balanza + self.volqueta + \
            self.analisis_laboratorio + self.otros_descuentos + self.retencion_acuerdo
        self.valor_reposicion = self.total_liquidacion_prov - self.regalia
        self.liquido_pagable = self.total_liquidacion_prov - self.total_descuento
    
    def calculo_factor_recuperacion(self):
        if self.tipo_carga == 'LAMA' and self.au < 3:
            return 0
        else:
            if self.tipo_carga == 'NORMAL' and self.au < 1:
                return 0
            else:
                factor = Factor.objects.filter(
                    rango_inferior__lte=self.au, rango_superior__gte=self.au)
                if factor:
                    return factor[0].factor_recuperacion * 100                        
    
class Muestra(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    carga = models.ForeignKey(
        Carga, on_delete=models.CASCADE)
    nombre = models.CharField(max_length=100, default='')
    codigo = models.CharField(max_length=20) 
    malla_mas = models.FloatField(default=0)
    malla_menos = models.FloatField(default=0)
    ley_ponderada = models.FloatField(default=0)
    nro_certif = models.CharField(max_length=20, default='')
    laboratorio = models.ForeignKey(
        Laboratorio, on_delete=models.CASCADE, null=True)
    css_class = models.CharField(max_length=20, default='')
    selected = models.BooleanField(default=False)
    deleted = models.BooleanField(default=False)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    def __str__(self) -> str:
        return f'{self.codigo} - {self.carga.numero} - {self.carga.color} {self.carga.numero_paleta}'

class Destare(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    vehiculo = models.ForeignKey(Vehiculo, on_delete=models.CASCADE)
    peso = models.FloatField(default=0)
    deleted = models.BooleanField(default=False)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    

produccion/models.py
from user.models import DestinoProduccion
import uuid
from django.db import models

# Create your models here.


class Produccion(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    minima_ley = models.FloatField(default=0)
    maxima_ley = models.FloatField(default=0)
    tms = models.FloatField(default=0)
    destino = models.ForeignKey(
        DestinoProduccion, on_delete=models.CASCADE)
    cargas = models.TextField(default='', blank=True)
    total_cargas = models.IntegerField(default=0)
    total_cargas_utilizadas = models.IntegerField(default=0)
    estado = models.BooleanField(default=False)
    deleted = models.BooleanField(default=False)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

produccion/forms.py
from django import forms

from .models import Produccion


class ProduccionCreateForm(forms.ModelForm):
    class Meta:
        model = Produccion
        fields = ('minima_ley', 'maxima_ley',
                  'destino', 'tms', 'cargas', 'total_cargas')
        widgets = {
            'minima_ley': forms.NumberInput(attrs={'class': 'form-control form-control-sm text-end'}),
            'maxima_ley': forms.NumberInput(attrs={'class': 'form-control form-control-sm text-end'}),
            'tms': forms.NumberInput(attrs={'class': 'form-control form-control-sm text-end', 'readonly': True}),
            'total_cargas': forms.NumberInput(attrs={'class': 'form-control form-control-sm text-end', 'readonly': True}),
            'cargas': forms.Textarea(attrs={'class': 'd-none'}),
            'destino': forms.Select(attrs={'class': 'form-control form-control-sm'}),
        }

produccion/templates/produccion/index.html
{% extends 'base.html' %}

{% load static %}

{% block css %}
    <link rel="stylesheet" href="{% static 'vendor/datatables/css/dataTables.bootstrap5.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/produccion/index.css' %}">
{% endblock css %}

{% block body %}
<div class="row">
    <div class="card">        
        <div class="card-body card-produccion">
            <div class="row">
                <div class="col-6">
                    <h5 class="card-title">Lista Produccion</h5>
                </div>                
                <div class="col-6 text-end">
                    <a href="{% url 'produccion-reporte-cancha' %}" class="btn btn-sm btn-warning"><i class="bi bi-printer"></i> Sin Procesar</a>
                    <a href="{% url 'produccion-nuevo' %}" class="btn btn-primary btn-sm">Nuevo</a>
                </div>
            </div>
            <hr/>
            <table id="produccion" class="table">
                <thead>
                    <tr>
                        <th>Fecha</th>
                        <th>Destino</th>
                        <th>Ley Minima</th>
                        <th>Ley Maxima</th>
                        <th>Total TMS</th>
                        <th>Total Cargas</th>
                        <th></th>
                    </tr>
                </thead>
                <tbody>
                    {% for produccion in objetos %}
                    <tr>
                        <td>{{ produccion.created|date:"d/m/Y"}}</td>
                        <td>{{ produccion.destino.nombre }}</td>
                        <td>{{ produccion.minima_ley }}</td>
                        <td>{{ produccion.maxima_ley }}</td>
                        <td>{{ produccion.tms }}</td>
                        <td>{{ produccion.total_cargas }}</td>
                        <td> <a href="{% url 'produccion-reporte' pk=produccion.id %}"><i class="bi bi-printer"></i></a> <a href="{% url 'produccion-cargas-view' pk=produccion.id %}"><i class="bi bi-eye"></i></a></td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
</div>
{% endblock body %}

{% block js %}    
    <script src="{% static 'vendor/datatables/js/jquery-3.5.1.js'%}"></script>
    <script src="{% static 'vendor/datatables/js/jquery.dataTables.min.js'%}"></script>
    <script src="{% static 'vendor/datatables/js/dataTables.bootstrap5.min.js'%}"></script>
    <script src="{% static 'js/produccion/index.js' %}"></script>
{% endblock js %}

produccion/templates/produccion/lista-cargas-ajax.html
<div class="row-carga">
    <div class="col1 dat1 rhead">Numero Boleta</div>
    <div class="col1 dat1 rhead">Fecha Pesaje</div>
    <div class="col2 dat1 rhead">Procedencia</div>
    <div class="col1 dat2 rhead">Tipo Carga</div>
    <div class="col1 dat1 rhead">Peso Neto</div>
    <div class="col1 dat3 rhead">TMS</div>
    <div class="col1 dat2 rhead">Au(g/Tn)</div>
    <div class="col1 dat3 rhead">Estado</div>
    <div class="col2 dat3 rhead">Color Paleta</div>
    <div class="col3 rhead"></div>
</div>
{% for carga in cargas %}
<div class="row-carga">
    <div class="d-none carga-id" data-id="{{ carga.id }}">{{ carga.id }}</div>
    <div class="col1 dat3">{{ carga.numero }}</div>
    <div class="col1 dat3">{{ carga.created|date:"d/m/Y"}}</div>
    <div class="col2 dat3">{{ carga.origen }}</div>
    <div class="col1">{{ carga.tipo_carga }}</div>
    <div class="col1 dat3">{{ carga.peso_neto_tn }}</div>
    <div class="col1 dat3 carga-tms" data-tms="{{ carga.tms_pagar }}" >{{ carga.tms_pagar }}</div>
    <div class="col1 dat2">{{ carga.au }}</div>
    <div class="col1 dat3">{% if carga.pagado %}PAGADO{% else %} {% if carga.liquido_pagable > 0 %}POR PAGAR {% else %}NO PAGAR {% endif %} {% endif %}</div>
    <div class="col2 dat3">{{ carga.numero_paleta }} {{ carga.color }}</div>
    <div class="col3"><i class="fa fa-minus-circle"></i></div>
</div>
{% endfor %}

produccion/templates/produccion/lista-cargas-ver.html
{% extends 'base.html' %}

{% load static %}

{% block css %}    
    <link rel="stylesheet" href="{% static 'css/produccion/nuevo.css' %}">
{% endblock css %}

{% block body %}
    <div class="row">
        <div class="card">
            <div class="card-body card-nuevo">
                <h5 class="card-title"></h5>
                <div class="row">                    
                    <div class="col-md-3">
                        <div class="row">
                            <label class="col-md-4 col-title col-form-label">Destino:</label>
                            <div class="col-md-8 col-form-label">{{ produccion.destino }}</div>
                        </div>
                    </div>
                    <div class="col-md-2">
                        <div class="row">
                            <label class="col-md-6 col-title col-form-label">Ley Minima:</label>
                            <div class="col-md-6 col-form-label">{{ produccion.minima_ley }}</div>
                        </div>
                    </div>
                    <div class="col-md-2">
                        <div class="row">
                            <label class="col-md-6 col-title col-form-label">Ley Maxima:</label>
                            <div class="col-md-6 col-form-label">{{ produccion.maxima_ley }}</div>
                        </div>
                    </div>
                    <div class="col-md-2">
                        <div class="row">
                            <label class="col-md-5 col-title col-form-label">Total TMS:</label>
                            <div class="col-md-7 col-form-label">{{ produccion.tms }}</div>
                        </div>
                    </div>
                    <div class="col-md-1">
                        <div class="row">                            
                        </div>
                    </div>                    
                    <div class="col-md-2">
                        <div class="row">
                            <div class="col-md-6 col-title col-form-label">Total Cargas: <span id="total_cargas" class="">{{ produccion.total_cargas }}</span></div>
                            <div class="col-md-6 text-end"><a href="{% url 'produccion-reporte' pk=produccion.id %}" class="btn btn-primary btn-sm">Imprimir</a></div>                            
                        </div>
                    </div>
                </div>
                <hr>
                <div class="row carga-list">
                    <div id="lista-cargas" class="col-md-12">
                        <div class="row-carga">
                        <div class="col1 dat1 rhead">Numero Boleta</div>
                        <div class="col1 dat1 rhead">Fecha Pesaje</div>
                        <div class="col2 dat1 rhead">Procedencia</div>
                        <div class="col1 dat2 rhead">Tipo Carga</div>
                        <div class="col1 dat1 rhead">Peso Neto</div>
                        <div class="col1 dat3 rhead">TMS</div>
                        <div class="col1 dat2 rhead">Au(g/Tn)</div>
                        <div class="col1 dat3 rhead">Estado</div>
                        <div class="col2 dat3 rhead">Color Paleta</div>
                        <div class="col3 rhead"></div>
                    </div>
                    {% for carga in produccion.carga_set.all %}
                    <div class="row-carga">
                        <div class="d-none carga-id" data-id="{{ carga.id }}">{{ carga.id }}</div>
                        <div class="col1 dat3">{{ carga.numero }}</div>
                        <div class="col1 dat3">{{ carga.created|date:"d/m/Y"}}</div>
                        <div class="col2 dat3">{{ carga.origen }}</div>
                        <div class="col1">{{ carga.tipo_carga }}</div>
                        <div class="col1 dat3">{{ carga.peso_neto_tn }}</div>
                        <div class="col1 dat3 carga-tms" data-tms="{{ carga.tms_pagar }}" >{{ carga.tms_pagar }}</div>
                        <div class="col1 dat2">{{ carga.au }}</div>
                        <div class="col1 dat3">{% if carga.pagado %}PAGADO{% else %} {% if carga.liquido_pagable > 0 %}POR PAGAR {% else %}NO PAGAR {% endif %} {% endif %}</div>
                        <div class="col2 dat3">{{ carga.numero_paleta }} {{ carga.color }}</div>
                        <div class="col3">
                            <i data-entrega="{% url 'produccion-entrega-view' pk=carga.id %}" class="bi {% if carga.estado_produccion %}bi-check-circle-fill{% else %}bi-bullseye{% endif %}">
                            </i><i data-remove="{% url 'produccion-carga-remove' pk=carga.id %}" class="bi bi-trash {% if carga.estado_produccion %}d-none{% endif %}"></i>
                        </div>
                    </div>
                    {% endfor %}
                    </div>
                </div>
            </div>
        </div>                
    </div>
{% endblock body %}

{% block js %}        
    <script src="{% static 'vendor/datatables/js/jquery-3.5.1.js'%}"></script>    
    <script src="{% static 'js/produccion/ver.js' %}"></script>
{% endblock js %}

produccion/templates/produccion/nuevo.html
{% extends 'base.html' %}

{% load static %}

{% block css %}
    <link rel="stylesheet" href="{% static 'vendor/select2/dist/css/select2.min.css' %}">
    <link rel="stylesheet" href="{% static 'vendor/select2/dist/css/select2-bootstrap4.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/produccion/nuevo.css' %}">
{% endblock css %}

{% block body %}
    <div class="row">
        <div class="card">
            <div class="card-body card-nuevo">
                <h5 class="card-title"></h5>
                <form class="row" action="" method="post">
                    {% csrf_token %}
                    <div class="col-md-2">
                        <div class="row">
                            <label class="col-md-4 col-title col-form-label">Destino</label>
                            <div class="col-md-8">{{ form.destino }}</div>
                        </div>
                    </div>
                    <div class="col-md-2">
                        <div class="row">
                            <label class="col-md-6 col-title col-form-label">Ley Minima</label>
                            <div class="col-md-6">{{ form.minima_ley }}</div>
                        </div>
                    </div>
                    <div class="col-md-2">
                        <div class="row">
                            <label class="col-md-6 col-title col-form-label">Ley Maxima</label>
                            <div class="col-md-6">{{ form.maxima_ley }}</div>
                        </div>
                    </div>
                    <div class="col-md-2">
                        <div class="row">
                            <label class="col-md-6 col-title col-form-label">Total TMS</label>
                            <div class="col-md-6">{{ form.tms }}</div>
                        </div>
                    </div>
                    <div class="col-md-1">
                        <div class="row">
                            <label class="col-md-8 col-title col-form-label" for="id_pagado">Pagado</label>
                            <div class="col-md-4 d-flex align-items-center"><input id="id_pagado" type="checkbox" name="pagado" checked></div>
                        </div>
                    </div>
                    {{ form.cargas }}
                    <div class="col-md-3">
                        <div class="row">
                            <div class="col-md-6 col-title col-form-label text-end">Total Cargas:</div>
                            <div class="col-md-4">{{ form.total_cargas }}</div>
                            <div class="col-md-2 text-end"><button type="submit" class="btn btn-primary btn-sm"><i class="bi bi-save"></i></button></div>                            
                        </div>
                    </div>
                </form>
                <hr>
                <div class="row carga-list">
                    <div id="lista-cargas" class="col-md-12">
                        
                    </div>
                </div>
            </div>
        </div>                
    </div>
{% endblock body %}

{% block js %}        
    <script src="{% static 'vendor/datatables/js/jquery-3.5.1.js'%}"></script>
    <script src="{% static 'vendor/select2/dist/js/select2.full.min.js' %}"></script>
    <script src="{% static 'vendor/select2/dist/js/i18n/es.js' %}"></script>
    <script src="{% static 'js/produccion/nuevo.js' %}"></script>
{% endblock js %}