user/urls.py
from django.urls import path
from django.conf.urls import url

from django.contrib.auth import views as auth_views

from .views import CotizacionDeleteView, CotizacionListJson, CotizacionUpdateView, CreateUserView, DestinoProduccionCreateView, DestinoProduccionListView, DestinoProduccionUpdateView, GeneradorPrintExcel, ParametroView, ProfileUpdateView, ConfiguracionView, UserEditView, UserListView, CotizacionCreateView, \
    DestinoCreateView, DestinoListView, DestinoUpdateView, LaboratorioListView, LaboratorioCreateView, LaboratorioUpdateView, GeneradorListJson, GeneradorCreateView, GeneradorPrintView, \
    UbicacionView, LaboratorioView, OrigenListView, OrigenCreateView, OrigenUpdateView, CodigoAutoComplete, FactorCreateView, FactorListView, FactorUpdateView

urlpatterns = [
    path('configuracion/', ConfiguracionView.as_view(), name='user-configuracion'),
    path('create/', CreateUserView.as_view(), name='user-create'),
    path('list/', UserListView.as_view(), name='user-list'),
    path('profile/<pk>/', ProfileUpdateView.as_view(), name='user-profile'),
    path('edit/<pk>/', UserEditView.as_view(), name='user-edit'),
    path('parametro/', ParametroView.as_view(), name='parametro-index'),
    path('parametro/ubicacion/', UbicacionView.as_view(),
         name='parametro-ubicacion-index'),
    path('parametro/laboratorio/', LaboratorioView.as_view(),
         name='parametro-laboratorio-index'),
    path('parametro/cotizacion/create/',
         CotizacionCreateView.as_view(), name='cotizacion-create'),
    path('parametro/cotizacion/edit/<pk>/',
         CotizacionUpdateView.as_view(), name='cotizacion-edit'),
    path('parametro/cotizacion/delete/<pk>/',
         CotizacionDeleteView.as_view(), name='cotizacion-delete'),
    url(r'^parametro/cotizacion/json/$',
        CotizacionListJson.as_view(), name='cotizacion-json'),
    path('parametro/origen/list/',
         OrigenListView.as_view(), name='origen-list'),
    path('parametro/origen/create/',
         OrigenCreateView.as_view(), name='origen-create'),
    path('parametro/origen/edit/<pk>/',
         OrigenUpdateView.as_view(), name='origen-edit'),
    path('parametro/destino/list/',
         DestinoListView.as_view(), name='destino-list'),
    path('parametro/destino/create/',
         DestinoCreateView.as_view(), name='destino-create'),
    path('parametro/destino/edit/<pk>/',
         DestinoUpdateView.as_view(), name='destino-edit'),
    path('parametro/destinoproduccion/list/',
         DestinoProduccionListView .as_view(), name='destinoproduccion-list'),
    path('parametro/destinoproduccion/create/',
         DestinoProduccionCreateView.as_view(), name='destinoproduccion-create'),
    path('parametro/destinoproduccion/edit/<pk>/',
         DestinoProduccionUpdateView.as_view(), name='destinoproduccion-edit'),
    path('parametro/laboratorio/list/',
         LaboratorioListView.as_view(), name='laboratorio-list'),
    path('parametro/laboratorio/create/',
         LaboratorioCreateView.as_view(), name='laboratorio-create'),
    path('parametro/laboratorio/edit/<pk>/',
         LaboratorioUpdateView.as_view(), name='laboratorio-edit'),
    url(r'^parametro/generador/json/$',
        GeneradorListJson.as_view(), name='generador-json'),
    path('parametro/generador/create/',
         GeneradorCreateView.as_view(), name='generador-create'),
    path('parametro/generador/reporte/<pk>/',
         GeneradorPrintView.as_view(), name='generador-reporte'),
    path('parametro/generador/reporte-excel/<pk>/',
         GeneradorPrintExcel.as_view(), name='generador-reporte-excel'),
    url(r'^codigo-autocomplete/$', CodigoAutoComplete.as_view(),
        name='codigo-autocomplete'),
    path('parametro/factor/create/',
         FactorCreateView.as_view(), name='factor-create'),
    path('parametro/factor/edit/<pk>/',
         FactorUpdateView.as_view(), name='factor-edit'),
    path('parametro/factor/list/',
         FactorListView.as_view(), name='factor-list'),
    path(
        'change-password/',
        auth_views.PasswordChangeView.as_view(
            template_name='user/change-password.html',
            success_url='/user/logout/'
        ),
        name='change_password_personal'
    ),
]

user/models.py
import uuid
from django.db import models
from django.contrib.auth.models import AbstractUser
from django.db.models import Q
from django.db.models.query import QuerySet

# Create your models here.
TIPO_ROL = (
    (0, 'GERENTE'),
    (1, 'ADMINISTRACION'),
    (2, 'PESAJE'),
    (3, 'PALETA'),
    (4, 'LABORATORIO'),
    (5, 'CONTABILIDAD'),
)

TIPO_PARAMETRO = (
    (0, 'COLOR'),
    (1, 'NUMERACION'),
    (2, 'CODIGO'),
)


class CustomUser(AbstractUser):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    photo = models.ImageField(
        upload_to='users/avatars/', null=True, blank=True)
    telefono = models.CharField(max_length=20, blank=True)
    rol = models.IntegerField(choices=TIPO_ROL, default=0)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    def __str__(self):
        return '{} {}'.format(self.first_name, self.last_name)

    def clean(self):
        self.first_name = self.first_name.upper()
        self.last_name = self.last_name.upper()


class Parametro(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    tipo = models.IntegerField(choices=TIPO_PARAMETRO, default=0)
    nombre = models.CharField(max_length=255)
    valor = models.CharField(max_length=255)
    deleted = models.BooleanField(default=False)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)


class Cotizacion(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    fecha_inicio = models.DateField()
    fecha_fin = models.DateField()
    valor_oficial = models.FloatField(default=0)
    valor_pagable = models.FloatField(default=0)
    deleted = models.BooleanField(default=False)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)


class Origen(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    nombre = models.CharField(max_length=100)
    costo_transporte = models.FloatField(default=0)
    deleted = models.BooleanField(default=False)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    def clean(self):
        self.nombre = self.nombre.upper()

    def __str__(self):
        return self.nombre


class Destino(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    nombre = models.CharField(max_length=100)
    deleted = models.BooleanField(default=False)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    def clean(self):
        self.nombre = self.nombre.upper()

    def __str__(self):
        return self.nombre


class Laboratorio(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    nombre = models.CharField(max_length=200)
    deleted = models.BooleanField(default=False)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.nombre

    def clean(self):
        self.nombre = self.nombre.upper()


class Generador(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    cantidad = models.IntegerField(default=0)
    deleted = models.BooleanField(default=False)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)


class CodigoMixin(object):

    def q_for_search_word(self, word):
        return Q(numero__icontains=word) & Q(utilizado=False)

    def q_for_search(self, search):
        q = Q()
        if search:
            searches = search.split()
            for word in searches:
                q = q & self.q_for_search_word(word)
        return q

    def filter_on_search(self, search):
        return self.filter(self.q_for_search(search))


class CodigoQuerySet(QuerySet, CodigoMixin):
    pass


class CondigoManager(models.Manager, CodigoMixin):

    def get_queryset(self):
        return CodigoQuerySet(self.model, using=self._db)


class Codigo(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    numero = models.CharField(max_length=100)
    cod_externo = models.CharField(max_length=100)
    cod_proveedor = models.CharField(max_length=100)
    cod_testigo = models.CharField(max_length=100)
    cod_bolsa = models.CharField(max_length=100)
    generador = models.ForeignKey(Generador, on_delete=models.CASCADE)
    utilizado = models.BooleanField(default=False)
    deleted = models.BooleanField(default=False)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    objects = CondigoManager()

    def __str__(self):
        return self.numero


class Factor(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    rango_inferior = models.FloatField(default=0)
    rango_superior = models.FloatField(default=0)
    factor_recuperacion = models.FloatField(default=0)
    sugerencia = models.FloatField(default=0)
    deleted = models.BooleanField(default=False)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)


class DestinoProduccion(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    nombre = models.CharField(max_length=200)
    deleted = models.BooleanField(default=False)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.nombre

    def clean(self):
        self.nombre = self.nombre.upper()

user/forms.py
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import UserCreationForm
import datetime

from django import forms
from django.forms import widgets

from .models import Cotizacion, CustomUser, Destino, DestinoProduccion, Factor, Generador, Laboratorio, Parametro, Origen


class CustomUserCreationForm(UserCreationForm):
    class Meta:
        model = get_user_model()
        fields = ('username', 'rol', 'password1', 'password2')
        widgets = {
            'username': forms.TextInput(attrs={'class': 'form-control form-control-sm'}),
            'rol': forms.Select(attrs={'class': 'form-select form-select-sm'}),
            'password1': forms.PasswordInput(attrs={'class': 'form-control form-control-sm'}),
            'password2': forms.PasswordInput(attrs={'class': 'form-control form-control-sm'}),
        }

    def __init__(self, *args, **kwargs):
        super(CustomUserCreationForm, self).__init__(*args, **kwargs)
        self.fields['password1'].widget = forms.PasswordInput(
            attrs={'class': 'form-control form-control-sm'})
        self.fields['password2'].widget = forms.PasswordInput(
            attrs={'class': 'form-control form-control-sm'})


class CustomUserUpdateForm(forms.ModelForm):
    class Meta:
        model = CustomUser
        fields = ('username', 'first_name', 'last_name',
                  'email', 'photo', 'telefono')
        widgets = {
            'username': forms.TextInput(attrs={'class': 'form-control form-control-sm'}),
            'first_name': forms.TextInput(attrs={'class': 'form-control form-control-sm uppercase'}),
            'last_name': forms.TextInput(attrs={'class': 'form-control form-control-sm uppercase'}),
            'email': forms.EmailInput(attrs={'class': 'form-control form-control-sm'}),
            'telefono': forms.TextInput(attrs={'class': 'form-control form-control-sm'}),
        }


class CustomUserEditForm(forms.ModelForm):
    class Meta:
        model = CustomUser
        fields = ('username', 'first_name', 'last_name', 'rol')
        widgets = {
            'username': forms.TextInput(attrs={'class': 'form-control form-control-sm'}),
            'first_name': forms.TextInput(attrs={'class': 'form-control form-control-sm'}),
            'last_name': forms.TextInput(attrs={'class': 'form-control form-control-sm'}),
            'rol': forms.Select(attrs={'class': 'form-select form-select-sm'}),
        }


class CotizacionForm(forms.ModelForm):
    class Meta:
        model = Cotizacion
        fields = ('fecha_inicio', 'fecha_fin',
                  'valor_oficial', 'valor_pagable')
        widgets = {
            'fecha_inicio': forms.DateInput(attrs={'class': 'fecha form-control form-control-sm'}),
            'fecha_fin': forms.DateInput(attrs={'class': 'fecha form-control form-control-sm'}),
            'valor_oficial': forms.NumberInput(attrs={'class': 'form-control form-control-sm'}),
            'valor_pagable': forms.NumberInput(attrs={'class': 'form-control form-control-sm'})
        }

    def __init__(self, *args, **kwargs):
        super(CotizacionForm, self).__init__(*args, **kwargs)
        self.fields['fecha_inicio'].initial = datetime.datetime.now()
        self.fields['fecha_fin'].initial = datetime.datetime.now()


class ColorEditForm(forms.ModelForm):
    class Meta:
        model = Parametro
        fields = ('nombre', 'valor')
        widgets = {
            'nombre': forms.HiddenInput(),
            'valor': forms.TextInput(attrs={'class': 'form-control form-control-sm color-picker'})
        }


class DestinoCreateForm(forms.ModelForm):
    class Meta:
        model = Destino
        fields = ('nombre',)
        widgets = {
            'nombre': forms.TextInput(attrs={'class': 'form-control form-control-sm uppercase'})
        }


class OrigenCreateForm(forms.ModelForm):
    class Meta:
        model = Origen
        fields = ('nombre', 'costo_transporte')
        widgets = {
            'nombre': forms.TextInput(attrs={'class': 'form-control form-control-sm uppercase'}),
            'costo_transporte': forms.NumberInput(attrs={'class': 'form-control form-control-sm'})
        }


class LaboratorioCreateForm(forms.ModelForm):
    class Meta:
        model = Laboratorio
        fields = ('nombre',)
        widgets = {
            'nombre': forms.TextInput(attrs={'class': 'form-control form-control-sm uppercase'})
        }


class GeneradorCreateForm(forms.ModelForm):
    class Meta:
        model = Generador
        fields = ('cantidad',)
        widgets = {
            'cantidad': forms.NumberInput(attrs={'class': 'form-control form-control-sm'})
        }


class FactorCreateForm(forms.ModelForm):
    class Meta:
        model = Factor
        fields = ('rango_inferior', 'rango_superior',
                  'factor_recuperacion', 'sugerencia')
        widgets = {
            'rango_inferior': forms.NumberInput(attrs={'class': 'form-control form-control-sm'}),
            'rango_superior': forms.NumberInput(attrs={'class': 'form-control form-control-sm'}),
            'factor_recuperacion': forms.NumberInput(attrs={'class': 'form-control form-control-sm'}),
            'sugerencia': forms.NumberInput(attrs={'class': 'form-control form-control-sm'})
        }


class DestinoProduccionCreateForm(forms.ModelForm):
    class Meta:
        model = DestinoProduccion
        fields = ('nombre',)
        widgets = {
            'nombre': forms.TextInput(attrs={'class': 'form-control form-control-sm uppercase'})
        }

user/templates/user/change-password.html
{% load bootstrap5 %}

<div class="card">
    <div class="card-body">
        <h5 class="card-title">
            CAMBIAR CONTRASENA
        </h5>
        <hr />
        <form id="form-password" method="post" action="{% url 'change_password_personal' %}">
            {% csrf_token %}
            <div class="row">
                <div class="col-md-8">
                    <div class="row">
                        <div class="col-md-12">{{ form.old_password.errors }}</div>            
                        <div class="col-md-5">{{ form.old_password.label_tag }}</div>
                        <div class="col-md-7">{{ form.old_password }}</div>                                                
                    </div>
                    <div class="row mt-3">
                        <div class="col-md-12">{{ form.new_password1.errors }}</div>
                        <div class="col-md-5">{{ form.new_password1.label_tag }}</div>
                        <div class="col-md-7">{{ form.new_password1 }}</div>                                                
                        {% if form.new_password1.help_text %}
                            <small class="form-text text-muted">{{ form.new_password1.help_text|safe }}</small>
                        {% endif %}
                    </div>
                    <div class="row mt-3">
                        <div class="col-md-12">{{ form.new_password2.errors }}</div>
                        <div class="col-md-5">{{ form.new_password2.label_tag }}</div>
                        <div class="col-md-7">{{ form.new_password2 }}</div>
                                                 
                        {% if form.new_password2.help_text %}
                            <div class="form-text text-muted">{{ form.new_password2.help_text|safe }}</div>
                        {% endif %}
                    </div> 
                    <div class="row mt-5">
                        <div class="col-md-9 text-end">
                            <a class="btn btn-secondary" href="{% url 'user-configuracion' %}">Volver</a>
                            <button class="btn btn-primary" type="submit">Guardar</button>
                        </div>                        
                    </div>                               
                </div>
            </div>            
        </form>
    </div>
</div>

user/templates/user/create.html
<div class="modal-header">
    <h5 class="modal-title">Registro de Usuario</h5>
</div>
<div class="modal-body">
    <form id="form-register-user" action="{% url 'user-create' %}" method="post">
    {% csrf_token %}
    <div class="row mb-2">
        <div class="col-md-6 col-sm-12">
            <label for="">Rol</label>
            {{ form.rol }}
            {{ form.rol.help_text }}
        </div>
    </div>
    <div class="row mb-2">
        <div class="col-md-12">
            <label for="">Nombre de Usuario</label>
            {{ form.username }}
            <small class="form-text text-muted">
                {{ form.username.help_text }}
            </small>            
        </div>
    </div>    
    <div class="row mb-2">
        <div class="col-md-12">
            <label for="">Contraseña</label>
            {{ form.password1 }}
            <small class="form-text text-muted">
                {{ form.password1.help_text }}
            </small>
        </div>
    </div>
    <div class="row mb-2">
        <div class="col-md-12">
            <label for="">Contraseña(confirmar)</label>
            {{ form.password2 }}
            <small class="form-text text-muted">
                {{ form.password2.help_text }}
            </small>            
        </div>
    </div>
    <div class="row">
        <div class="col-md-12 text-end">
            <button type="button" class="btn btn-sm btn-secondary" data-bs-dismiss="modal">Cancelar</button>
            <button type="submit" class="btn btn-sm btn-primary">Guardar</button>
        </div>
    </div>    
    </form>
</div>

user/templates/user/edit.html
<div class="modal-header">
    <h5 class="modal-title">Editar Usuario</h5>
</div>
<div class="modal-body">
    <form id="usuario-form" action="{% url 'user-edit' pk=object.id %}" method="post" autocomplete="off">
        {% csrf_token %}                
        <div class="row mb-2">
            <div class="col-md-6 col-sm-12">
                <label for="">Rol</label>
                {{ form.rol }}
                {{ form.rol.help_text }}
            </div>
        </div>        
        <div class="row mb-2">
            <div class="col-md-12 col-sm-12">
                <label for="">Nombre de Usuario</label>
                {{ form.username }}
                <small class="form-text text-muted">
                    {{ form.username.help_text }}
                </small>            
            </div>
        </div>
        <div class="row mb-2">
            <div class="col-md-12">
                <label for="">Nombres</label>
                {{ form.first_name }}
                {{ form.first_name.help_text }}
            </div>
        </div>        
        <div class="row mb-2">
            <div class="col-md-12">
                <label for="">Apellidos</label>
                {{ form.last_name }}
                {{ form.last_name.help_text }}
            </div>
        </div>        
        <div class="row">
            <div class="col-md-12 text-end">
                <button type="button" class="btn btn-sm btn-secondary" data-bs-dismiss="modal">Cancelar</button>
                <button type="submit" class="btn btn-sm btn-primary">Guardar</button>
            </div>
        </div>
    </form>
</div>

user/templates/user/list.html
{% load static %}

{% load usuario_tags %}

<div class="card">
    <div class="card-body">
        <div class="row mb-2">
            <div class="col-md-6">
                <h5 class="card-title">
                LISTA DE USUARIOS
                </h5>
            </div>
            <div class="col-md-6 text-end">
                <button id="user-register" class="btn btn-sm btn-primary" data-url="{% url 'user-create' %}">NUEVO</button>
            </div>
        </div>
        <div class="row">
            <div class="col-md-12">
                <table id="usuario-list" class="table table-hover table-responsive">
                    <thead>
                        <tr>
                            <th scope="col">#</th>
                            <th scope="col">Usuario</th>
                            <th scope="col">Nombre</th>
                            <th scope="col">Rol</th>
                            <th></th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for usuario in object_list %}
                        <tr>
                            <th scope="row">{{ forloop.counter }}</th>
                            <td>{{ usuario.username }}</td>
                            <td>{{ usuario }}</td>
                            <td>{{ usuario.rol|rol_usuario }}</td>
                            <td class="cotizacion-options text-end"><i data-url="{% url 'user-edit' pk=usuario.id %}" class="bi bi-pencil-square"></i></td>
                        </tr>                
                        {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>        
    </div>
</div>

<!-- Modal -->
<div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered">
        <div class="modal-content">
            
        </div>
    </div>
</div>

user/templates/user/profile.html
{% load static %}

{% load bootstrap5 %}
<div class="card">
    <div class="card-body">
        <h5 class="card-title">
            MI PERFIL
        </h5>
        <form id="edit-user-form" action="{% url 'user-profile' pk=request.user.id %}" class="form-container" method="post" enctype="multipart/form-data">
            <div class="row">        
                <div class="col-md-4 avatar-user text-center">                        
                    {% if request.user.photo %}
                    <img id="preview-img" src="{{ request.user.photo.url }}" alt="" class="img-fluid">
                    {% else %}
                    <img id="preview-img" src="{% static 'images/avatar-placeholder-large.png' %}" alt="" class="img-fluid">
                    {% endif %}                    
                    <label for="id_photo" class="btn btn-primary">ADJUNTAR FOTO</label>
                    <div class="photo-content">
                        {{ form.photo }}
                    </div>                    
                    {% csrf_token %}            
                </div>
                <div class="col-md-8">
                    <div class="row">
                        <div class="col-md-8 mb-2">                    
                            <label for="">Nombre de Usuario</label>
                            {{ form.username }}
                            <small class=                    {{ form.username.help_text}}
                            </small>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-md-8 mb-2">                    
                            <label for="">Nombres</label>
                            {{ form.first_name }}
                            <small class="form-text text-muted">
                                {{ form.first_name.help_text}}
                            </small>
                        </div>
                    </div>  
                    <div class="row">
                        <div class="col-md-8 mb-2">                    
                            <label for="">Apellidos</label>
                            {{ form.last_name }}
                            <small class="form-text text-muted">
                                {{ form.last_name.help_text}}
                            </small>
                        </div>
                    </div>           
                    <div class="row">
                        <div class="col-md-8 mb-2">                    
                            <label for="">Dirección de correo electrónico</label>
                            {{ form.email }}
                            <small class="form-text text-muted">
                                {{ form.email.help_text}}
                            </small>
                        </div>
                    </div>                                    
                    <div class="row">
                        <div class="col-md-8 mb-2">                    
                            <label for="">Telefono</label>
                            {{ form.telefono }}
                            <small class="form-text text-muted">
                                {{ form.telefono.help_text}}
                            </small>
                        </div>
                    </div> 
                    <div class="row">
                        <div class="col-md-8 text-end">
                            <button id="cambiar-password" data-url="{% url 'change_password_personal' %}" type="button" class="btn btn-secondary me-2">CAMBIAR CONTRASENA</button><button type="submit" class="btn btn-primary ">GUARDAR CAMBIOS</button>
                        </div>
                    </div>
                </div>    
            </div>                                                                        
        </form>    
    </div>
</div>